<a href="https://colab.research.google.com/github/hyunjung930/sesac-web/blob/main/%ED%86%B5%EA%B3%84%EB%B6%84%EC%84%9D%EC%8B%9C%EA%B0%81%ED%99%94_Numpy%EC%86%8C%EA%B0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 소개

In [1]:
import numpy as np

numpy는 선형 시퀀스를 배열로 개체로 취급

선형 시퀀스  ex )리스트, 튜플... 등


In [ ]:
ls = [1,2,3]
arr = np.array(ls)
print(arr)

In [4]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
print("구조:",arr.shape)
print("차원:",arr.ndim)  # 1차원: 선 표현 2차원:면 3차원: 공간 

구조: (3,)
차원: 1


다차원 배열

In [6]:
ls = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
arr = np.array(ls)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
print("구조:",arr.shape)
print("차원:",arr.ndim)  # 1차원: 선 표현 2차원:면 3차원: 공간 

구조: (4, 3)
차원: 2


#다양한 방법의 생성

In [12]:
z_arr = np.zeros(10) # Numpy의 제로수
print(z_arr)
print("구조:",z_arr.shape)
print("차원:",z_arr.ndim)  
print("원소 형식: ",z_arr.dtype) #float64: 64비트의 float

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
구조: (10,)
차원: 1
원소 형식:  float64


In [11]:
z_arr = np.zeros(10,dtype=int) # 원하는 형식으로 가능하다. 
print(z_arr)
print("구조:",z_arr.shape)
print("차원:",z_arr.ndim)  
print("원소 형식:",z_arr.dtype) #파이썬의 int는 8bit 사이즈를 갖고있다.

[0 0 0 0 0 0 0 0 0 0]
구조: (10,)
차원: 1
원소 형식: int64


In [13]:
z_arr = np.zeros((2,3)) #파일 명시 없을 시, 디폴트인 float으로 표현
print(z_arr)
print("구조:",z_arr.shape)
print("차원:",z_arr.ndim) 
print("원소 형식:",z_arr.dtype) 

[[0. 0. 0.]
 [0. 0. 0.]]
구조: (2, 3)
차원: 2
원소 형식: float64


In [18]:
def view_arr_info(arr):
  print(arr)
  print("구조:",arr.shape)
  print("차원:",arr.ndim) 
  print("원소 형식:",arr.dtype) 

In [21]:
z_arr = np.zeros((3,2,4),dtype = int)
view_arr_info(z_arr)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
구조: (3, 2, 4)
차원: 3
원소 형식: int64


In [22]:
o_arr = np.ones(10)
view_arr_info(o_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
구조: (10,)
차원: 1
원소 형식: float64


In [23]:
s_arr = np.arange(100)
view_arr_info(s_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조: (100,)
차원: 1
원소 형식: int64


In [24]:
s_arr = np.arange(50,100) #50~100까지의 숫자를 리스트로 표현
view_arr_info(s_arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
구조: (50,)
차원: 1
원소 형식: int64


In [28]:
r_arr = np.random.randint(0,100,size=10,dtype=int) #랜덤한 정수 출력
view_arr_info(r_arr)

[75  3 49 39 77 27 76 91 23 50]
구조: (10,)
차원: 1
원소 형식: int64


#기본적인 사용


In [30]:
a1 = np.arange(1,100)
view_arr_info(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
구조: (99,)
차원: 1
원소 형식: int64


In [31]:
print(a1[4]) # 인덱스를 통해 원소에 접근
a1[4]=9
print(a1[4])

5
9


In [32]:
print(a1[2:8]) # 슬라이스를 통해 부분 원소를 선택
print(a1[:8])
print(a1[8:])

[3 4 9 6 7 8]
[1 2 3 4 9 6 7 8]
[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80
 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [34]:
a1 = np.arange(0,100) # numpya array는 정확한 값이 들어가야 오류 없음
view_arr_info(a1)
a2 = a1.reshape(5,20)
view_arr_info(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조: (100,)
차원: 1
원소 형식: int64
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
구조: (5, 20)
차원: 2
원소 형식: int64


In [36]:
print(a2[0]) #인덱스 0인 원소 : 리스트[0,1,2,,,,,,,,19]
print(a2[0][2]) #인덱스 0인 원소: 리스트[0,1,2,,,,,,,,19]의 인덱스 2인 원소

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2


In [37]:
#음의 정수로 인덱스를 표현하면 뒤에서부터 접근(-1부터 시작)
print(a2[0][-1]) #인덱스 0인 원소: 리스트[0,1,2,,,,,,,,19]의 인덱스 -1인 원소

19


#구조변경

In [38]:
a1 = np.arange(100)
view_arr_info(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조: (100,)
차원: 1
원소 형식: int64


In [41]:
a4 = a1.reshape(20,-1) # 20* 5로 표현 
view_arr_info(a4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
구조: (20, 5)
차원: 2
원소 형식: int64


In [42]:
a1 = np.arange(784)
view_arr_info(a1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [45]:
a2 = a1.reshape(28,-1) 
view_arr_info(a2)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
   46  47  48  49  50  51  52  53  54  55]
 [ 56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
   74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
  102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
  130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159 160 161 162 163 164 165 166 167]
 [168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185
  186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213
  214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 23

# 쉬어가는 코너

In [47]:
from tensorflow import keras

In [48]:
data = keras.datasets.mnist.load_data() #손글씨 데이터를 다운로드

11501568/11490434 [==============================] - 0s 0us/step


In [49]:
train_data,test_data = data #학습용 데이터,평가용 데이터로 분리
image_train, label_train = train_data #이미지, 실제값

In [52]:
print(image_train.shape) # 이미지도 넘파이 배열으로 표현가능
print(label_train.shape)

(60000, 28, 28)
(60000,)


In [60]:
for r in range(28):
  for c in range(28):
    if(image_train[0][r][c] == 0):
      print("  ",end='')
    else:
      print("☞",end='')
  print()
#print(label_train[0]) #손글씨

                                                        
                                                        
                                                        
                                                        
                                                        
                        ☞☞☞☞☞☞☞☞☞☞☞☞        
                ☞☞☞☞☞☞☞☞☞☞☞☞☞☞☞☞        
              ☞☞☞☞☞☞☞☞☞☞☞☞☞☞☞☞          
              ☞☞☞☞☞☞☞☞☞☞☞                    
                ☞☞☞☞☞☞☞  ☞☞                    
                  ☞☞☞☞☞                            
                      ☞☞☞☞                          
                      ☞☞☞☞                          
                        ☞☞☞☞☞☞                    
                          ☞☞☞☞☞☞                  
                            ☞☞☞☞☞☞                
                              ☞☞☞☞☞                
                                  ☞☞☞☞              
                            ☞☞☞☞☞☞☞              
                        ☞☞☞☞